# Generated by Django 3.2.6 on 2021-08-26 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0002_rename_name_hospital_hospital'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesperson',
            old_name='user',
            new_name='sales',
        ),
    ]
